# Generated by Django 4.2.8 on 2025-07-22 03:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.CharField(blank=True, max_length=250, null=True)),
                ('ensurance', models.BooleanField(default=False)),
                ('national_code', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('national_code', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('share_percent', models.IntegerField(default=70)),
                ('birthday', models.CharField(blank=True, max_length=250, null=True)),
                ('study', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, to='clinic.coursetitle')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('creted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('pay_month', models.IntegerField(default=1)),
                ('pay_year', models.IntegerField(default=1403)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_sessions', models.IntegerField(default=0)),
                ('cost_paid', models.IntegerField(default=0)),
                ('register_date', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.customer')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.instructor')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.coursetitle')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorMonthlyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=1403)),
                ('is_paid', models.BooleanField(default=False)),
                ('pay_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('courses', models.ManyToManyField(blank=True, to='clinic.reservedcourse')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.instructor')),
            ],
        ),
    ]
