# Generated by Django 4.2.8 on 2025-07-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_customer_ensurance_sessionreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionfile',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
