# Generated by Django 4.2.8 on 2025-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_prescriptionfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
