# Generated by Django 4.2.8 on 2025-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_sessionreport_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='instructormonthlyincome',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='instructormonthlyincome',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
        migrations.RemoveField(
            model_name='reservedcourse',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservedcourse',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='reservedcourse',
            name='title',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CourseTitle',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='InstructorMonthlyIncome',
        ),
        migrations.DeleteModel(
            name='ReservedCourse',
        ),
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
    ]
