# Generated by Django 4.2.8 on 2025-07-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_instructor_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ensurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
